Algoritmo "AtividadeManzanoLaçoPARA(E)"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Exibir todosos número inteiros de 1 a 20
// Autor(a)    : Elton luiz
// Data atual  : 03/04/2023
Var
// Seção de Declarações das variáveis 
contadora,numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 1 ate 20 passo 2 faca
numero<-numero+contadora
Escreval(contadora)
fimpara

Fimalgoritmo