Algoritmo "AtividadeManzanoPagina46B"
// Disciplina   : [ Lógica de Programação]
// Professor   : Obama
// Descrição   :
// Autor(a)    : Sala
// Data atual  : 29/03/2023
Var
    soma, numero : inteiro
Inicio
    numero <- 1
    enquanto (numero <= 100) faca
        escreva (numero, "+")
        soma <- soma + numero
        numero <- numero + 1
    fimenquanto
    escreva ("A soma dos inteiros de 1 à 100 é: ", soma)
Fimalgoritmo