Algoritmo "Atividade52"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Escrever os 10 primeiros números inteiros após o 100
// Autor(a)    : Elton Luiz
// Data atual  : 29/03/2023
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contadora<- 100
enquanto contadora<111 faca
escreval("Numero:", contadora)
contadora<- contadora+1
fimenquanto

Fimalgoritmo