Algoritmo "Atividade51"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Escrever um algoritimo de 1 a 10 em ordem decrescente
// Autor(a)    : Elton Luiz
// Data atual  : 29/03/2023
Var
// Seção de Declarações das variáveis 
contadora:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contadora<-10
enquanto contadora>=1 faca
escreval("Número:" , contadora)
contadora<- contadora-1)
fimenquanto

Fimalgoritmo