Algoritmo "AtividadeManzanoPagina46C"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Somar os números pares de 1 a 500
// Autor(a)    : Sala
// Data atual  : 29/03/2023
Var
    soma, numero : inteiro
Inicio
    numero <- 0
    enquanto (numero <= 500 ) faca
        escreval (numero, "+")
        soma <- soma + numero
        numero <- numero + 2
    fimenquanto
    escreva (" A soma dos pares de 2 à 500 é: ", soma)
Fimalgoritmo

